apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverfort-deployment
  labels:
    app: silverfort-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: silverfort-app
  template:
    metadata:
      labels:
        app: silverfort-app
    spec:
      containers:
        - name: silverfort-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTAINER_NAME
              value: {{ .Values.env.CONTAINER_NAME | quote }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000